victoire_core:
    widgets:
        ArticleList:
            class: "Victoire\\Widget\\ArticleListBundle\\Entity\\WidgetArticleList"
            name: ArticleList
            parent: Listing

twig:
    form:
        resources:
            - LexikFormFilterBundle:Form:form_div_layout.html.twig
