services:
    victoire_core.twig.widget_articlelist_manager:
        class: Victoire\ArticleListBundle\Widget\Manager\WidgetArticleListManager
        arguments: [@service_container]

    widget_articlelist_manager:
        alias: victoire_core.twig.widget_articlelist_manager
